### ISSUE TITLE
crash 1.21

### ISSUE THREAD

**Issue by The1389Henry** [BlazeClient/BlazeClient-mod#2]
When I start 1.21 iy will will crash

**Comment by NoboKik** [comment]
Send crash report (can be found in .minecraft/crash-reports/)

**Comment by The1389Henry** [comment]
content://net.kdt.pojavlaunch.scoped.gamefolder/document/%2Fstorage%2Femulated%2F0%2FAndroid%2Fdata%2Fnet.kdt.pojavlaunch%2Ffiles%2F.minecraft%2Fcrash-reports%2Fcrash-2024-08-23_09.30.11-client.txt

**Comment by The1389Henry** [comment]
Copy it and paste-

**Comment by The1389Henry** [comment]
https://www.mediafire.com/file/1fr9lkay0gowsdd/crash-2024-08-23_09.36.04-client.txt/file

**Comment by The1389Henry** [comment]
https://www.mediafire.com/file/1fr9lkay0gowsdd/crash-2024-08-23_09.36.04-client.txt/file

**Comment by The1389Henry** [comment]
> Send crash report (can be found in .minecraft/crash-reports/)

https://www.mediafire.com/file/1fr9lkay0gowsdd/crash-2024-08-23_09.36.04-client.txt/file

**Comment by The1389Henry** [comment]
How to fix?

**Comment by NoboKik** [comment]
It seems like you are using pojav launcher, it is not supported.
